### ISSUE TITLE
Use of Concourse fonts

### ISSUE THREAD

**Issue by mbutterick** [MaxGabriel/maxgabriel.github.com#1]
I notice that you’re using my copyrighted Concourse fonts [on your website](http://maxgabriel.github.io), and also redistributing them through this repo. 

1) Have you paid for them? I’m afraid I can’t find your name in my customer database.

2) Whether you’ve paid for them or not, you can’t put them in a public repo. Sorry.

**Comment by MaxGabriel** [comment]
Hi, I'm not sure if you'd receive a notification about this since I've made the repo private. I emailed you with my license information.
